### PR TITLE
Recalculate data item usage statistics in the COD, revision 296817

### PR DESCRIPTION
**Pull request by vaitkus**
Statistics were recalculated using gemmi 0.5.3.

### CODE REVIEW

**Comment by wojdyr** [comment]
I waited with the reply because I was about to modify `gemmi tags`.
Recently, I added showing most popular values, if there are <1000 distinct values for a given tag. Today I extended it further. See [tags.html](https://project-gemmi.github.io/pdb-stats/tags.html).

For example,  for`_diffrn_radiation.pdbx_diffrn_protocol` it is

> 180245×{line} 6723×{word} 5×{0.9796 - 1.2}     ☞ 61 distinct values (96.4% SINGLE WAVELENGTH, 3.2% MAD, …)

for `_refine.pdbx_ls_cross_valid_method`

> 7×{text} 42989×{line} 121043×{word} 6×{0 - 15822}     ☞ 261 distinct values (71.3% THROUGHOUT, 25.1% FREE R-VALUE, 2.1% NONE, …)

for `_struct_conn.ptnr1_symmetry`

> 14381960×{word}     ☞ 463 distinct values (99.91% 1_555, 0.00% 3_555, …)

I was actually missing this information. At some point I wanted to check how often in the last example we have something else than 1_555, and last week there was discussion why we have both "THROUGHOUT" and "FREE R-VALUE", so I wanted to check which one is more popular.
For many tags these examples are not useful and only clutter the table, it's hard to distinguish it automatically.
 
I haven't looked into COD for a while and I can update accept this PR if you wish, but first check how it looks now for PDB tags.

**Comment by vaitkus** [comment]
I think that this is a great a addition that should definitely be extended to the COD as well.

What exactly should I do to get the updated representation of the COD statistics? Would it suffice to update to the latest version of gemmi and run the old command:
<pre>
$ gemmi tags --full path/to/cod/cif/ > cod-cif-tags.tsv
$ gemmi tags --full --glob='*.hkl' path/to/cod/hkl/ > cod-hkl-tags.tsv
$ sed -i s"/ on 20..-..-../ on $(date -Idate)/" cod-tags.html
</pre>

P.S. The table *might* look better if the distinct values are put in a separate column although that would also result in a lot of empty cells.

**Comment by wojdyr** [comment]
There were also changes in the html file, I just copied them to cod-tags.html.
Yes, the same commands should work, with gemmi compiled from git.

**Comment by wojdyr** [comment]
I didn't expect it. Is it much slower now than before?
The size of `mmcif-tags.tsv` increased from 232KB to 324KB, so I thought that `cod-cif-tags.tsv` would have a similar increase. It'd be good to keep these files well under 1MB.
I guess there is no real benefit in including these large fields. I can add an option to trim them to N characters. I suppose N=100 or 200 would be sufficient. Or is there a better way to keep the file small?

**Comment by vaitkus** [comment]
> I didn't expect it. Is it much slower now than before?

I only tested the website on localhost so I did not notice a change in performance at all.
As for gemmi, I did not time it, so it is hard to even guesstimate.

> The size of mmcif-tags.tsv increased from 232KB to 324KB, so I thought that cod-cif-tags.tsv would have a similar increase. It'd be good to keep these files well under 1MB.

I had a look at the summary file and the main culprit for the increased size are the embedded SHELX and HKL files. If I remove the first 25 tags with largest values, the size of the file gets reduced to 614 K. See for example, information on the largest 10 values:

| Tag  | Total line length |
| ------------- | ------------- |
| _jana_m95_file | 83378676 |
| _jana_m90_file | 39262660 |
| _shelx_original_hkl_file | 5394376 |
| _shelx_fcf_file | 4860743 |
| _hkl_file | 4439784 |
| _iucr_refine_structure_details | 3022517 |
| _shelxl_hkl_file | 2645476 |
| _iucr_refine_hkl_file | 2494991 |
| _shelx_hkl_file_presqueezed | 2449574 |
| _xd_hkl_file | 2106219 |

A similar trend is also seen in the HKL tag file, although, there it only sums up to ~8 MB.

> I guess there is no real benefit in including these large fields. I can add an option to trim them to N characters. I suppose N=100 or 200 would be sufficient. Or is there a better way to keep the file small?
 
There is definitely no need to include such fields in full. Trimming all fields to the first N symbols would definitely work, however, you may end up with all identical trimmed values for a given data item, e.g. all embedded data files may have the same header.

Another possible approach could be to omit specific values for items with extremely long  values altogether, e.g. if there is at least one value longer than, let's say 1000 characters, output only the number of distinct values (if possible).

**Comment by wojdyr** [comment]
I pushed a quick change. It should trim values to a given limit. You can change the limit in the source code, by changing the number in line:

    constexpr int VALUE_LENGTH_LIMIT = 128;

It's not really tested – I wanted to make this change today. If it doesn't work, I'll improve tomorrow.

**Comment by vaitkus** [comment]
Thank you for the update. I have recalculated the statistics with the newest version on gemmi and the file sizes are now much more manageable (under 0.5 MB). Website with the trimmed values also looks good, IMHO (see the updated PR).

**Comment by vaitkus** [comment]
Thanks!

**Pull request merged**
